apiVersion: v1
kind: Service
metadata:
  namespace: gradlepc
  name: gradlepc-svc
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gradle-petclinic
